# Generated by Django 5.0.6 on 2024-05-21 15:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="first_name",
            field=models.CharField(
                max_length=30, validators=[accounts.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="last_name",
            field=models.CharField(
                max_length=30, validators=[accounts.validators.validate_name]
            ),
        ),
    ]
