# Generated by Django 5.0.6 on 2024-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="newspapers"
            ),
        ),
    ]
