# Generated by Django 5.0.6 on 2024-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="topic",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topic",
            field=models.ManyToManyField(
                related_name="newspapers",
                to="board.topic"),
        ),
    ]
