# Generated by Django 5.0.6 on 2024-05-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_newspaper_main_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="main_topic",
        ),
    ]
